### ISSUE TITLE
Incentive testnet documentation

### ISSUE THREAD

**Issue by syabro** [stratosnet/sds#111]
https://github.com/stratosnet/sds/wiki/Tropos-Incentive-Testnet

Some things are not clear:

> Commonly-used node operations 
1. It doesn't sound like a required step
2. Steps before were starting with a verb like "Run". Maybe rename it to something like "Setup wallet and get STOS"

> By default, faucet will send 10stos
Is it enough for testing? Maybe add a line about it?

**Comment by TEPOTPOH** [comment]
Also please provide _SPList: NetworkAddress_
```
SPList: 
  NetworkAddress: TBA
```

**Comment by hong-pang** [comment]
> Also please provide _SPList: NetworkAddress_
> 
> ```
> SPList: 
>   NetworkAddress: TBA
> ```

This has to be provided at the launch time.

**Comment by hong-pang** [comment]
since no more comments for several days, we will close this issue.
