### ISSUE TITLE
Crash logs

### ISSUE THREAD

**Issue by espoir1989** [stratosnet/sds#128]
[DEBUG]2022/03/08 00:18:50 client.go:51: on connect
[DEBUG]2022/03/08 00:18:50 conn.go:131: read start
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x78 pc=0x47541e2]

goroutine 3865 [running]:
github.com/stratosnet/sds/framework/client/cf.(*ClientConn).GetName(0x4c329d0)
	/Users/espoir/Desktop/work/sds/framework/client/cf/conn.go:177 +0x22
github.com/stratosnet/sds/pp/peers.checkSingleSpLatency({0xc0001c8270, 0x12}, 0x80)
	/Users/espoir/Desktop/work/sds/pp/peers/sp_peers.go:152 +0x2e5
github.com/stratosnet/sds/pp/peers.SendLatencyCheckMessageToSPList()
	/Users/espoir/Desktop/work/sds/pp/peers/sp_peers.go:129 +0x127
created by github.com/stratosnet/sds/pp/event.ReqHBLatencyCheckSpList
	/Users/espoir/Desktop/work/sds/pp/event/heart.go:44 +0xe5

**Comment by mdumaisqsnetwork** [comment]
Fixed by https://github.com/stratosnet/sds/pull/134
