### ISSUE TITLE
Can't startmining 

### ISSUE THREAD

**Issue by TemplateXu** [stratosnet/sds#179]
[DEBUG]2022/04/26 10:55:14 register_to_sp.go:93: get RspMining &{35.73.160.68:8888 {0xbde780 0xbdec40 0xbde880 0xbde800 100 false true true 7} 0 0xc000624538 0xc000622510 0xc000622530 0xc0008f6f60 0xc0008f6fc0 {0 0} 35.73.160.68:8888 [] 0xc000628000 0x5082a0 [0xc000636fc0 0xc000637030] 66 0 0xc0006224e0 0xc0006224e8 250 0xc0006224f0 0 0xc0006224f8 0 0xc000622500 0 0xc000622508 false}
[DEBUG]2022/04/26 10:55:14 requests.go:694: Received message type = *protos.RspMining msgBuf len = 42
[DEBUG]2022/04/26 10:55:14 requests.go:704: target =  result:{state:RES_FAIL msg:"Cannot sync stake with stratos chain"}
[INFO]2022/04/26 10:55:14 register_to_sp.go:100: Cannot sync stake with stratos chain

**Comment by mdumaisqsnetwork** [comment]
This happened due to a temporary problem on the SP nodes (action couldn't be broadcast). Closing because there is nothing specific to do
